"""Office Workspace Scenario V2 contracts and deterministic world kernel."""

from __future__ import annotations

OFFICE_V2_CONTRACT_SCHEMA_VERSION = "office-v2.0"
OFFICE_V2_CANONICAL_WORLD_ID = "office-world-v2.0"
OFFICE_V2_CANONICAL_JSON_VERSION = "canonical-json-v1"
OFFICE_V2_TOOL_CONTRACT_VERSION = "office-v2-tools-1.1"
OFFICE_V2_TOOL_CATALOG_VERSION = "office-v2-tool-catalog-v1"
OFFICE_V2_TASK_CATALOG_VERSION = "office-v2-task-catalog-v1"
OFFICE_V2_AGENT_SURFACE_VERSION = "office-v2-agent-surface-v1"
OFFICE_V2_AGENT_CONTEXT_VERSION = "office-v2-agent-context-v1"
OFFICE_V2_INTERACTION_SESSION_VERSION = "office-v2-interaction-session-v1"
OFFICE_V2_ATTACK_CONTRACT_VERSION = "office-v2-attack-contract-v1"
OFFICE_V2_ATTACK_OBJECTIVE_CATALOG_VERSION = "office-v2-attack-objectives-v1.1"
OFFICE_V2_ATTACK_FIELD_REGISTRY_VERSION = "office-v2-attack-fields-v1"
OFFICE_V2_REACHABILITY_VERSION = "office-v2-reachability-v1"
OFFICE_V2_ATTACK_CASE_CATALOG_VERSION = "office-v2-attack-cases-v1"
OFFICE_V2_ATTACK_MATERIALIZER_VERSION = "office-v2-attack-materializer-v1"
OFFICE_V2_ORACLE_CONTRACT_VERSION = "office-v2-oracle-contract-v1"
OFFICE_V2_ORACLE_EVIDENCE_VERSION = "office-v2-oracle-evidence-v1"

__all__ = [
    "OFFICE_V2_CANONICAL_JSON_VERSION",
    "OFFICE_V2_CANONICAL_WORLD_ID",
    "OFFICE_V2_CONTRACT_SCHEMA_VERSION",
    "OFFICE_V2_AGENT_CONTEXT_VERSION",
    "OFFICE_V2_AGENT_SURFACE_VERSION",
    "OFFICE_V2_INTERACTION_SESSION_VERSION",
    "OFFICE_V2_ATTACK_CASE_CATALOG_VERSION",
    "OFFICE_V2_ATTACK_CONTRACT_VERSION",
    "OFFICE_V2_ATTACK_FIELD_REGISTRY_VERSION",
    "OFFICE_V2_ATTACK_MATERIALIZER_VERSION",
    "OFFICE_V2_ATTACK_OBJECTIVE_CATALOG_VERSION",
    "OFFICE_V2_REACHABILITY_VERSION",
    "OFFICE_V2_ORACLE_CONTRACT_VERSION",
    "OFFICE_V2_ORACLE_EVIDENCE_VERSION",
    "OFFICE_V2_TASK_CATALOG_VERSION",
    "OFFICE_V2_TOOL_CATALOG_VERSION",
    "OFFICE_V2_TOOL_CONTRACT_VERSION",
]
